name: Build Dockerfile

on:
  push:
    paths:
      - .github/workflows/build-docker.yaml
      - Dockerfile
      - src/**
      - data/**.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}
          docker build .
