name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - src/app/**
      - .github/workflows/Deploy.yaml
      - Dockerfile

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        run: |
          heroku container:login
          heroku container:push web -a ${HEROKU_APP_NAME}
          heroku container:release web -a ${HEROKU_APP_NAME}
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
