name: Sync the character list
on:
  push: {}
  schedule:
    - cron: 0 * * * *
concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Install Tesseract
        run: |
          sudo apt -y update && sudo apt -y install tesseract-ocr libtesseract5 libtesseract-dev
          mkdir -p /opt/tesseract/share/tessdata
          curl -L https://github.com/tesseract-ocr/tessdata_best/raw/main/eng.traineddata -o /opt/tesseract/share/tessdata/eng.traineddata
          curl -L https://github.com/tesseract-ocr/tessdata_best/raw/main/jpn.traineddata -o /opt/tesseract/share/tessdata/jpn.traineddata
          curl -L https://github.com/tesseract-ocr/tessdata_best/raw/main/jpn_vert.traineddata -o /opt/tesseract/share/tessdata/jpn_vert.traineddata
          tesseract --version

      - name: Run a headless-shell
        run: |
          docker run -d -p 9222:9222 --rm --name headless-shell chromedp/headless-shell

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.0'

      - name: Sync
        env:
          TESSDATA_PREFIX: /opt/tesseract/share/tessdata
        run: |
          make genlist
          git diff
