trainable:
  names:
    - "アグネスタキオン"
    - "ウイニングチケット"
    - "ウオッカ"
    - "エアグルーヴ"
    - "エルコンドルパサー"
    - "オグリキャップ"
    - "カレンチャン"
    - "キングヘイロー"
    - "グラスワンダー"
    - "ゴールドシップ"
    - "サイレンススズカ"
    - "サクラバクシンオー"
    - "シンボリルドルフ"
    - "スーパークリーク"
    - "スペシャルウィーク"
    - "タイキシャトル"
    - "ダイワスカーレット"
    - "テイエムオペラオー"
    - "トウカイテイオー"
    - "ナイスネイチャ"
    - "ナリタタイシン"
    - "ハルウララ"
    - "ビワハヤヒデ"
    - "マチカネフクキタル"
    - "マヤノトップガン"
    - "ミホノブルボン"
    - "メジロマックイーン"
    - "メジロライアン"
    - "ライスシャワー"
